# Generated by Django 4.2 on 2023-05-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asanpay', '0003_bannedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
