# Generated by Django 4.2 on 2023-05-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asanpay', '0004_contactmodel_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='hidden_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
