# Generated by Django 4.2 on 2023-05-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asanpay', '0005_remove_contactmodel_is_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='hidden_type',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
