# Generated by Django 4.2 on 2023-05-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asanpay', '0006_alter_contactmodel_hidden_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
